### ISSUE TITLE
scheduler endpoint showing number of workers connected and their IPs

### ISSUE THREAD

**Issue by mpictor** [EdSchouten/bazel-buildbarn#12]
Something I'd like to have is the ability to find the IPs of workers connected to a scheduler, probably through an endpoint on the scheduler. Does this sound like something that'd be useful and fairly easy to add?

**Comment by EdSchouten** [comment]
I have thought about this in the past as well and I think it's a great idea. I was thinking that we should at some point gain a status page that not only shows the list of builders, but also gives insight in which actions they are running/ran.

Whether it's feasible to add: sure. But the question is at what point in time we'd like to add this. The current LocalBuildExecutor would be the logical place to cram this in, but that thing currently has quite some technical debt. I can imagine that LocalBuildExecutor also needs to be completely rebuilt if we consider implementing #7. Maybe good to combine those efforts?

**Comment by mpictor** [comment]
Combining them makes sense to me, or at least waiting until #7 is done.

**Comment by EdSchouten** [comment]
Based on this feature request, I had a discussion with @mickael-carl. One of the downsides of putting a 'heavy' web page into the scheduler is that it's going to need access to the CAS/AC to show any meaningful details on actions it executed.

This is something we'd rather prevent. What we're going to do is that we'll develop a new process (dubbed `bbb_browser`) that will allow you to explore the CAS/AC. To click through Action, Command, Tree and Directory objects and eventually download blobs. This can already be developed right now on top of the existing blobstore/cas/ac layers that are stable-ish.

This will allow the scheduler process to remain simple, as it can simply link to `bbb_browser` to show all of the gory details.

**Comment by mpictor** [comment]
The browser looks nice, but I thought error messages from the worker were supposed to contain browser urls now? So far, I've seen the urls printed to the worker's log, but not in bazel's output.

**Comment by EdSchouten** [comment]
This is something we're working on improving. Right now Bazel's remote execution protocol doesn't have any designated field for passing these URLs through, meaning that they can only be obtained for build failures by running `bazel build --verbose_failures` and manually opening up the log file printed at the top of Bazel's output (likely called `/home/..../bbb_worker`).

I'm currently working on getting the protocol extended to have a string field for passing the URL through: https://github.com/bazelbuild/remote-apis/pull/36/files

**Comment by EvyBongers** [comment]
Since https://github.com/bazelbuild/remote-apis/pull/36/files has been merged, can you give an update on when this could be implemented?

**Comment by EdSchouten** [comment]
Closing this issue in favour of https://github.com/buildbarn/bb-remote-execution/issues/1. This repo is going to get archived, as the project is going to be renamed to just Buildbarn.

Thanks for reporting!
