### ISSUE TITLE
Syntax error in cmd/bbb_browser/templates/view_command.html: Unexpected "=" in operand (line 13)

### ISSUE THREAD

**Issue by mmikitka** [EdSchouten/bazel-buildbarn#14]
Here is the error message upon starting //cmd/bbb_browser:bbb_browser_container

```
bbb-browser_1_53da211186e1 | panic: template: view_command.html:13: unexpected "=" in operand
bbb-browser_1_53da211186e1 | 
bbb-browser_1_53da211186e1 | goroutine 1 [running]:
bbb-browser_1_53da211186e1 | main.main()
bbb-browser_1_53da211186e1 | 	cmd/bbb_browser/main.go:40 +0x629
```

The solution seems to be changing `=` to `:=` on line 13

**Comment by mmikitka** [comment]
I'm working on a PR for this now

**Comment by EdSchouten** [comment]
Hey,

This is odd. According to https://golang.org/pkg/text/template/#hdr-Variables, this should be permitted. Which version of `rules_go` are you using to build Buildbarn? The one declared in WORKSPACE, or another one?

**Comment by mmikitka** [comment]
I cloned `EdSchouten/bazel-buildbarn` and ran `bazel run //cmd/bbb_browser:bbb_browser_container` in the repo, so I'm using the version of `rules_go` in the bazel-buildbarn WORKSPACE file.

**Comment by EdSchouten** [comment]
Gotcha. Slightly annoying about our setup is that we always build Buildbarn as an external within another repository that pins to another version of Go. Can you replace `rules_go` in `WORKSPACE` with the following and let me know whether that works for you?

```
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "f87fa87475ea107b3c69196f39c82b7bbf58fe27c62a338684c20ca17d1d8613",
    url = "https://github.com/bazelbuild/rules_go/releases/download/0.16.2/rules_go-0.16.2.tar.gz",
)
```

**Comment by EdSchouten** [comment]
I just tested this. Indeed: we need a more recent version of Go to make variable assignments in templates work. Thanks for reporting!
