### ISSUE TITLE
Don't declare the HOME directory for the build user in source (rely on /etc/passwd)

### ISSUE THREAD

**Issue by mmikitka** [EdSchouten/bazel-buildbarn#16]
The build user's home directory is declared to `/tmp` in `tools/debian8_base/etc/passwd` and also declared to the same value in `pkg/builder/local_build_executor.go`. It seems best to make /etc/passwd the authoritative source for the home directory.

This is causing me problems because I need to override the build user's home directory to store SSH keys, and the home directory (/tmp) is wiped clean by the bbb_worker binary.

**Comment by EdSchouten** [comment]
The latest version of Buildbarn no longer does this, as `bbb_worker` has been overhauled to delegate execution to a helper process `bbb_runner`. Eventually this helper process should regain the functionality to clear out home directories, /tmp, set `$HOME`, etc. but that shall be tracked separately from this issue.

Thanks for reporting!
