### ISSUE TITLE
Building locally with Bazel

### ISSUE THREAD

**Issue by macroorganizm** [EdSchouten/bazel-buildbarn#21]
Hi, we need some help with connecting BuildBarn with Bazel locally.
We run the BuildBarn via Docker compose and see in console that all works:
```
➜ docker-compose ps            
                         Name                                        Command               State                      Ports                    
-----------------------------------------------------------------------------------------------------------------------------------------------
docker-compose_bbb-browser_1_f8412f650b7f                 /bbb_browser                     Up      0.0.0.0:7983->80/tcp                        
docker-compose_bbb-frontend_1_e763be8e6dc9                /bbb_frontend -scheduler=d ...   Up      0.0.0.0:7980->80/tcp, 0.0.0.0:8980->8980/tcp
docker-compose_bbb-runner-debian8_1_142cf2eb2921          /bbb_runner -temp-director ...   Up                                                  
docker-compose_bbb-runner-ubuntu16-04_1_38352797bf43      /bbb_runner -temp-director ...   Up                                                  
docker-compose_bbb-scheduler-debian8_1_37d2dde9f5df       /bbb_scheduler                   Up      0.0.0.0:7981->80/tcp, 8981/tcp              
docker-compose_bbb-scheduler-ubuntu16-04_1_c7d5b6d73f9f   /bbb_scheduler                   Up      0.0.0.0:17981->80/tcp, 8981/tcp             
docker-compose_bbb-storage-0_1_2b74c7d9f5cc               /bbb_storage                     Up      0.0.0.0:7982->80/tcp, 8982/tcp              
docker-compose_bbb-storage-1_1_d18b854e8b4b               /bbb_storage                     Up      0.0.0.0:17982->80/tcp, 8982/tcp             
docker-compose_bbb-worker-debian8_1_198d9c9f4ffd          /bbb_worker -browser-url=h ...   Up      0.0.0.0:7984->80/tcp                        
docker-compose_bbb-worker-ubuntu16-04_1_e6778ec11f40      /bbb_worker -browser-url=h ...   Up      0.0.0.0:17984->80/tcp
```
but when we try to run the bazel build on the runned instance we will see, that something went wrong:
```
bazel build :bundle --remote_executor=http://localhost:8980  --spawn_strategy=remote --strategy=Typescript=remote --genrule_strategy=remote
ERROR: Failed to connect to 'http://localhost:8980': cannot find a NameResolver for http://localhost:8980
ERROR: Error initializing RemoteModule
```
also we tried to use option `remote_instance_name` with different names, (e.g. container name: --remote_instance_name=docker-compose_bbb-frontend_1_e763be8e6dc9), but anyway received such errors.
Obviously, we missed something, but we can't understand what exactly. Could you help with it?

**Comment by EdSchouten** [comment]
Hi there! I think in your case things are breaking, because you shouldn't prefix the hostname with `http://`. It's connecting to the frontend using GRPC, which isn't necessarily HTTP. Just use `--remote_executor=localhost:8980`.

Do note that `run.sh` has some instructions at the top that show what you can add to your `~/.bazelrc` to use Buildbarn. Enjoy!

**Comment by EvilAlexei** [comment]
@EdSchouten thank you for your answer and for a hint about `http://`.
Maybe you can give us advice on what options in `~/.bazelrc` can cause this kind of issues,
or what can be missing?

**Comment by EdSchouten** [comment]
Hi Oleksii,

All I wanted to say is that it's wisest to first start out with only placing the configuration options in `~/.bazelrc` that are listed in `deployments/docker-compose/run.sh` and nothing else. Then it should be sufficient to just run `bazel build --config=bbb-debian8 //...` to make builds work. Using that should just work out of the box. There is no need to pass in anything else on the command line.
