### ISSUE TITLE
bazel client on macos, cpu vs host_cpu

### ISSUE THREAD

**Issue by mkmik** [EdSchouten/bazel-buildbarn#5]
Hi!

I'm trying to use buildbarn from a macos client and I get:

```
; bazel build --cpu=k8 --crosstool_top=@bazel_buildbarn//toolchain:debian9  --experimental_strict_action_env --remote_executor=address.of.my.buildbarn.deployment.here.com:8980 --remote_instance_name=debian9 --spawn_strategy=remote --strategy=Closure=remote --strategy=Javac=remote //foobar
ERROR: No default_toolchain found for cpu 'darwin'. Valid cpus are: [
  k8,
]
```

**Comment by mmikulicic** [comment]
it seems `--host_cpu=k8` would work (didn't try end to end, since I'm still setting up my bbb instance)

**Comment by EdSchouten** [comment]
Hi there,

Thanks for reporting this issue. I have to confess I haven't tested using Bazel Buildbarn using different operating systems/CPUs on the client side. Be sure to let me know whether using `--host_cpu` fixes this for you definitively and I'll update the documentation!
